f = open('/Users/hb/Downloads/file1.txt', 'w')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.write('This is my first file. This will close: no silly pop up messages.\n')
f.close()

with open('/Users/hb/Downloads/file1.txt', 'r') as f:
    me = f.readlines()

print me

counter = 0.0
for rid in me:
    if counter % 2 == 0:
        print counter, rid
    counter = counter + 1

with open('/Users/hb/Downloads/file1.txt', 'w') as f:
    for rid in me:
        if counter % 2 == 0:
            f.write('xyz\n')
        else:
            f.write(rid)
        counter = counter + 1

a = open('/Users/hb/Downloads/file1.txt', 'a')
a.write('this is fun\n')
a.close()

